name: Java CI test with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      # Checkout del repository
      - uses: actions/checkout@v4

      # Imposta JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Build e Test con Maven
      - name: Build and Run Tests
        run: mvn clean verify -Dtest=!it.univaq.cdvd.testLogicaGui.**

      # Report dei risultati
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
