# Workflow aggiornato
name: Java CI test with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      # Checkout del repository
      - uses: actions/checkout@v4

      # Installazione di Docker
      - name: Build and Test in Docker
        run: |
          docker build -t javafx-ci --file .github/workflows/env.dockerfile .
          docker run --rm javafx-ci

      # Report dei risultati
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
